name: Update Image URLs

on:
  push:
    paths:
      - 'images/**/*'

jobs:
  update_image_list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate image_urls.json
        run: |
          mkdir -p output
          echo "[" > output/image_urls.json
          first=1
          find ./images -type f -name "*.png" | while read -r img; do
            [ $first -eq 0 ] && echo "," >> output/image_urls.json
            echo "  {\"name\": \"$(basename "$img")\", \"url\": \"https://raw.githubusercontent.com/${{ github.repository }}/main/${img#./}\"}" >> output/image_urls.json
            first=0
          done
          echo "]" >> output/image_urls.json

      - name: Copy image_urls.json to repo
        run: cp output/image_urls.json ./image_urls.json

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and Push if changed
        run: |
          git add image_urls.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update image URLs [auto]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





